variables:
  PLUGIN_NAME: 'scieloSubmissionsReport'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs/unit_tests.yml'